name: Publish MzcAirPrompt via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths: [ '.github/workflows/**', 'src/**' ]

permissions:
  contents: write  # GitHub Pages 브랜치 푸시에 필요

jobs:
  build-blazor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Publish Blazor Project
        run: dotnet publish ./src/MzcAirPrompt/MzcAirPrompt.csproj -c Release -o release --nologo

      - name: Upload wwwroot folder
        uses: actions/upload-artifact@v4
        with:
          name: blazor-wwwroot
          path: release/wwwroot

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs: [build-blazor]
    steps:
      - uses: actions/checkout@v4

      - name: Download wwwroot folder
        uses: actions/download-artifact@v4
        with:
          name: blazor-wwwroot
          path: release/wwwroot

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
