name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore src/MzcAirPrompt/MzcAirPrompt.csproj

    - name: Build
      run: dotnet build src/MzcAirPrompt/MzcAirPrompt.csproj --no-restore --configuration Release

    - name: Publish .NET Core Project
      run: dotnet publish src/MzcAirPrompt/MzcAirPrompt.csproj -c Release -o release --nologo    # 커스텀 도메인 사용 시에는 base href를 "/"로 유지
    # GitHub Pages 서브디렉토리 배포가 아닌 커스텀 도메인 사용 시에는 base href 변경 불필요
    
    # 커스텀 도메인 설정을 위한 CNAME 파일 생성
    - name: Create CNAME file for custom domain
      run: echo 'prompts.aiready.ai.kr' > release/wwwroot/CNAME

    # .nojekyll 파일이 있는지 확인하고 없으면 생성
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
        force_orphan: true
